# Generated by Django 3.0.5 on 2022-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20221212_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(default='pizza_pics/default.jpg', upload_to='pizza_pics,'),
        ),
    ]
