# Generated by Django 3.0.5 on 2022-12-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_pizza_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(default='pizza_pics/default.jpg', upload_to='pizza_pics'),
        ),
    ]
